const cityDatabase = {
    "New York city, New York": { pop: 8478072, desc: "The 'Big Apple,' a global hub of finance, culture, and the most populous city in the US." },
    "Los Angeles city, California": { pop: 3878704, desc: "The 'Entertainment Capital of the World,' home to Hollywood and massive Pacific ports." },
    "Chicago city, Illinois": { pop: 2721308, desc: "The 'Windy City,' famous for its bold architecture and deep-dish pizza." },
    "Houston city, Texas": { pop: 2390125, desc: "Known as 'Space City,' it is home to NASA's Johnson Space Center." },
    "Phoenix city, Arizona": { pop: 1673164, desc: "The 'Valley of the Sun,' the only state capital with over a million people." },
    "Philadelphia city, Pennsylvania": { pop: 1573916, desc: "The 'City of Brotherly Love,' where the Declaration of Independence was signed." },
    "San Antonio city, Texas": { pop: 1526656, desc: "Home to the Alamo and the famous scenic River Walk." },
    "San Diego city, California": { pop: 1404452, desc: "Known as 'America's Finest City,' famous for its zoo and naval base." },
    "Dallas city, Texas": { pop: 1326087, desc: "A major commercial hub known as 'Big D,' famous for its arts district." },
    "Jacksonville city, Florida": { pop: 1009833, desc: "The largest city by area in the contiguous United States." },
    "Fort Worth city, Texas": { pop: 1008106, desc: "Where the 'West begins,' famous for its Stockyards and western heritage." },
    "San Jose city, California": { pop: 997368, desc: "The 'Capital of Silicon Valley,' center of the world's tech industry." },
    "Austin city, Texas": { pop: 993588, desc: "The 'Live Music Capital of the World' and the capital of Texas." },
    "Charlotte city, North Carolina": { pop: 943476, desc: "A major banking center and the home of the NASCAR Hall of Fame." },
    "Columbus city, Ohio": { pop: 933263, desc: "The state capital of Ohio and home to one of the largest universities in the US." },
    "San Francisco city, California": { pop: 827526, desc: "Famous for the Golden Gate Bridge, cable cars, and steep hills." },
    "Seattle city, Washington": { pop: 780995, desc: "The 'Emerald City,' birthplace of Starbucks and home to the Space Needle." },
    "Denver city, Colorado": { pop: 729019, desc: "The 'Mile High City,' located exactly one mile above sea level." },
    "Oklahoma City city, Oklahoma": { pop: 712919, desc: "A major livestock market and the capital of Oklahoma." },
    "Washington city, District of Columbia": { pop: 702250, desc: "The nation's capital, filled with monuments and the seat of government." },
    "Boston city, Massachusetts": { pop: 673458, desc: "One of the oldest cities in the US, known for its key role in the American Revolution." },
    "Detroit city, Michigan": { pop: 645705, desc: "The 'Motor City,' famous for being the heart of the US auto industry." },
    "Portland city, Oregon": { pop: 635749, desc: "Known for its parks, bridges, bicycle friendliness, and eco-friendliness." },
    "Las Vegas city, Nevada": { pop: 678922, desc: "The 'Entertainment Capital of the World,' famous for its vibrant nightlife." },
    "Baltimore city, Maryland": { pop: 568271, desc: "A historic seaport and the birthplace of 'The Star-Spangled Banner'." },
    "Milwaukee city, Wisconsin": { pop: 563531, desc: "Known for its brewing traditions and located on the shores of Lake Michigan." },
    "Albuquerque city, New Mexico": { pop: 560326, desc: "Host to the world's largest hot air balloon festival." },
    "Tucson city, Arizona": { pop: 554013, desc: "Surrounded by mountain ranges and home to the University of Arizona." },
    "Fresno city, California": { pop: 550105, desc: "The agricultural hub of the San Joaquin Valley." },
    "Sacramento city, California": { pop: 535798, desc: "The state capital of California, born during the Gold Rush." },
    "Atlanta city, Georgia": { pop: 520070, desc: "A major cultural hub and host of the 1996 Summer Olympics." },
    "Kansas City city, Missouri": { pop: 516032, desc: "Famous for its barbecue and its many beautiful fountains." },
    "Miami city, Florida": { pop: 487014, desc: "A major center of finance, commerce, and international trade." },
    "Minneapolis city, Minnesota": { pop: 428579, desc: "One half of the Twin Cities, divided by the Mississippi River." }
};
